Repository opea-project/GenAIInfra, pull requests merged in 2024-11, with the labels that each got.

#539 Helm Chart for AgentQnA
  helm-charts/agentqna/.helmignore
  helm-charts/agentqna/Chart.yaml
  helm-charts/agentqna/README.md
  helm-charts/agentqna/gaudi-values.yaml
  helm-charts/agentqna/templates/_helpers.tpl
  helm-charts/agentqna/templates/crag.yaml
  helm-charts/agentqna/templates/docretriever.yaml
  helm-charts/agentqna/templates/tests/test-pod.yaml
  helm-charts/agentqna/values.yaml
  helm-charts/common/agent/.helmignore
  helm-charts/common/agent/Chart.yaml
  helm-charts/common/agent/README.md
  helm-charts/common/agent/ci-gaudi-values.yaml
  helm-charts/common/agent/gaudi-values.yaml
  helm-charts/common/agent/templates/_helpers.tpl
  helm-charts/common/agent/templates/configmap.yaml
  helm-charts/common/agent/templates/deployment.yaml
  helm-charts/common/agent/templates/service.yaml
  helm-charts/common/agent/templates/servicemonitor.yaml
  helm-charts/common/agent/templates/tests/test-pod.yaml
  helm-charts/common/agent/values.yaml
  helm-charts/common/tgi/templates/configmap.yaml
Labels: enhancement, V1.1

#567 Only set HABANA_LOGS env in gaudi case
  helm-charts/common/tgi/templates/configmap.yaml
  helm-charts/common/vllm/templates/configmap.yaml
  microservices-connector/config/manifests/tgi.yaml
  microservices-connector/config/manifests/tgi_nv.yaml
  microservices-connector/config/manifests/vllm.yaml
Labels: V1.1

#572 README pointing to ghcr.io package
  helm-charts/README.md
  helm-charts/agentqna/README.md
  helm-charts/audioqna/Chart.yaml
  helm-charts/common/agent/README.md
  helm-charts/common/gpt-sovits/Chart.yaml
  microservices-connector/config/manifests/gpt-sovits.yaml
Labels: V1.1

#575 Rename image name XXX-hpu to XXX-gaudi
  helm-charts/common/llm-uservice/ci-vllm-gaudi-values.yaml
  helm-charts/common/vllm/gaudi-values.yaml
  helm-charts/common/vllm/templates/configmap.yaml
  microservices-connector/config/manifests/vllm_gaudi.yaml
Labels: WIP

#593 Fix VisualQnA & AudioQnA
  helm-charts/audioqna/README.md
  helm-charts/visualqna/templates/deployment.yaml
Labels: V1.1

#603 Fix audioqna readme for cached MODELDIR
  helm-charts/audioqna/README.md
Labels: V1.1
